### ISSUE TITLE
Feat: '통신 오류' 페이지 구현 작업

### ISSUE THREAD

**Issue by kitae0831** [hminah0215/tomatoes#11]
## 설명

'통신 오류' 페이지 구현 작업

## 기대 효과

사용자가 원인을 명확히 이해하고 문제 해결을 시도할 수 있도록 안내 
-> 인터넷 연결 오류와 같은 서버 측 문제는 보통 500번대 에러

## TODO

- [x]  페이지에 필요한 asset 정리
- [x]  통신 오류 페이지 디자인 및 내용 작성
- [x]  PC, MO 반응형에 맞게 디자인

## 추가 정보

<img width="611" alt="스크린샷 2024-10-16 오후 4 13 54" src="https://github.com/user-attachments/assets/68563b42-6a83-4010-80f1-f7ccf849fcc7">
