### ISSUE TITLE
Feat: 홈 화면 디자인 작업 마무리

### ISSUE THREAD

**Issue by StopSoo** [hminah0215/tomatoes#19]
## 설명

홈 화면 디자인 작업 1차에서 구현하지 못 한 스와이프 컴포넌트들을 구현.
다른 화면에서 불러와야 하는 컴포넌트들의 작업이 끝나면 불러오기.

## 기대 효과

✨ 메인 화면 완성 ✨
## TODO

- [x] 메인에 걸릴 자동 스와이프 컴포넌트 구현.
- [x] 공모전, 대외활동 수동 스와이프 컴포넌트 구현.
- [ ] 매거진 컴포넌트 완성 시 불러오기.

## 추가 정보

<img width="704" alt="378402649-776a9be8-db90-40cb-8165-17f75c594fa1" src="https://github.com/user-attachments/assets/aa17ac79-fe8e-4382-ae79-3316f4a32258">
