### ISSUE TITLE
Feat: 공모전 및 대외활동 페이지 디자인

### ISSUE THREAD

**Issue by starcradle101** [hminah0215/tomatoes#20]
## 설명
본 이슈는 공모전 및 대외활동 페이지의 레이아웃을 구현하는 이슈입니다.

## 기대 효과
- 이제 공모전 및 레이아웃 화면을 확인할 수 있습니다.
- 공통으로 사용 가능한 필터 및 검색 컴포넌트를 구현해 코드의 재사용성을 높일 수 있습니다.

## TODO
- [ ] 필터 컴포넌트 구현하기
- [ ] 검색 컴포넌트 구현하기
- [ ] 공모전 및 대외활동 페이지 레이아웃 구현하기

## 추가 정보
레이아웃 구현 후 기능 구현 예정입니다.
