### ISSUE TITLE
Feat: 매거진 페이지 디자인 

### ISSUE THREAD

**Issue by hminah0215** [hminah0215/tomatoes#24]
# Issue 제목

## 설명
매거진 (토마토PICK, 매거진상세페이지, 토마토 TIP, 수상작 갤러리, 토마토리포트) 페이지
레이아웃을 구현합니다.

일단 pc 화면 기준으로 작업하고 추후 반응형 수정할 예정입니다. 

## 기대 효과
매거진 페이지, 매거진 하위의 페이지를 확인 할 수 있습니다.

## TODO

- [x] 매거진 메뉴 헤더 컴포넌트 구현 
- [x] 매거진 페이지에서 사용하는 assets 모음 
- [x] 매거진 검색창 
- [x] 매거진 리포트페이지 (커스텀 alert 컴포넌트 추가)
- [x] 매거진 수상작갤러리 페이지
- [x] 토마토Tip 페이지 
- [x] 토마토 pick 페이지 일부분
