### ISSUE TITLE
Refactor: 1차 리팩토링 진행

### ISSUE THREAD

**Issue by starcradle101** [hminah0215/tomatoes#32]
## 설명
본 이슈에서는 현재까지 진행된 작업 내역을 토대로 프로젝트의 1차적인 리팩토링을 진행하고자 합니다.

## 기대 효과
- 폴더 구조를 개선합니다.
    - `containers` 폴더를 사용한 페이지와 컴포넌트의 분리
    - `utils` 폴더를 사용한 유틸리티 함수 분리
    - `hooks` 폴더를 사용한 커스텀 훅의 분리
- `tailwind.config.ts`에 containers 경로 추가
- 파일 네이밍 세분화
- 최상위 레이아웃 스타일 설정

## TODO
- [ ] containers 경로를 Tailwind CSS config에 추가
- [ ] `containers` 폴더 생성 및 기존 컴포넌트 이동
- [ ] `globals.css`에서 사용되고 있는 내비게이션 컴포넌트 관련 스타일링을 해당 컴포넌트 내부로 이동
- [ ] 

## 추가 정보
이슈를 진행하며 추가적인 내역이 발생할 경우 추가할 예정입니다.
