### ISSUE TITLE
Feat: 공통 페이지네이션 및 그리드 컴포넌트 구현

### ISSUE THREAD

**Issue by starcradle101** [hminah0215/tomatoes#35]
# 설명
#13 이슈에서 페이지네이션을 위한 공통 컴포넌트를 한차례 구현한 바가 있습니다. 그러나 이 컴포넌트는 여러 페이지에서 공용으로 사용되기에 어려웠고, 따라서 보다 유연한 페이지네이션 컴포넌트를 다시 구현하기 위해 본 이슈를 생성했습니다.

페이지네이션 컴포넌트는 다음과 같이 구성되어 있습니다.

- `Pagination`
    - `GridView`
        - `GridItem`
    - `PaginationControl`

본 이슈에서는 각각의 컴포넌트를 차례차례 개선할 예정입니다. 우선 `GridView` 컴포넌트부터 아래와 같은 형태로 개선 예정입니다.
```tsx
type GridGap = {
  x: number;
  y: number;
};

type GridViewProps<T> = {
  items: T[];
  GridItem: React.ComponentType<{ item: T }>;
  columns: {
    mobile: number;
    web: number;
  };
  gaps: {
    mobile: GridGap;
    web: GridGap;
  };
};

export default function GridViewTest<T>({
  items,
  GridItem,
  columns,
  gaps,
}: GridViewProps<T>) {
  const gridClass = `
    grid
    sm:grid-cols-${columns.mobile} 
    md:grid-cols-${columns.web} 
    gap-x-${gaps.mobile.x} 
    gap-y-${gaps.mobile.y} 
    md:gap-x-${gaps.web.x} 
    md:gap-y-${gaps.web.y}
  `;

  return (
    <div className={`grid w-full ${gridClass}`}>
      {items.map((item, index) => (
        <GridItem key={index} item={item} />
      ))}
    </div>
  );
}
```

이와 같이 GridView를 개선하면, 예전처럼 `usePathname`을 사용하지 않고 사용자가 직접 파라미터를 설정해 보다 유연하게 GridView를 설정할 수 있습니다.

```tsx
// 사용 예시
<GridViewTest
  items={magazines}
  GridItem={MagazineGridItem}
  columns={{ mobile: 2, web: 4 }}
  gaps={{ mobile: { x: 2, y: 3 }, web: { x: 4, y: 6 } }}
/>
```

# 기대 효과
- 페이지네이션 컴포넌트를 다양한 곳에서 자유롭게 사용할 수 있습니다.
- 웹/모바일 간 전환이 사용자의 페이지네이션 사용 경험을 해치지 않습니다.

# TODO
- [x] `GridView` 컴포넌트 개선
- [x] `GridItem` 컴포넌트 개선
- [x] `PaginationControl` 컴포넌트 개선
- [x] `Pagination` 컴포넌트 개선

# 추가 정보
