### ISSUE TITLE
design: 홈 화면 전반적인 css 수정 및 크롤링 데이터와의 연결

### ISSUE THREAD

**Issue by StopSoo** [hminah0215/tomatoes#38]
## 설명

지난 중간 발표까지의 작업 이후로 전반적인 리팩토링을 진행.

## 기대 효과

홈 화면만의 레이아웃 설정을 통한 깔끔한 디자인 구현.
크롤링 코드와 컴포넌트들을 연결함으로써, 실제 데이터를 사용하여 구현.

## TODO

- [X] 홈 화면의 레이아웃 설정 
- [x] 크롤링 코드와 각 컴포넌트들을 연결  
- [ ] 모바일 버전 메인 슬라이더 구현
