### ISSUE TITLE
Feat: 공모전 및 대외활동 데이터 크롤링 작업

### ISSUE THREAD

**Issue by starcradle101** [hminah0215/tomatoes#44]
## 설명
본 이슈에서는 토마토들 프로젝트에서 사용하는 공모전 및 대외활동 데이터에 대한 다양한 기능을 구현하고 작업을 진행하고자 합니다.

## 기대 효과
- 크롤링으로 정제된 공모전 및 대외활동 데이터 획득
- Supabase에 공모전 및 대외활동 데이터 업로드 가능
- 해당 데이터를 다룰 수 있는 Supabase query 구현

## TODO
- [ ] 공모전 및 대외활동 데이터 모델 및 타입 구체화
- [ ] 공모전 및 대외활동 크롤링 스크립트 작성
- [ ] 해당 데이터를 Supabase에 업로드할 수 있도록 route 추가
- [ ] Supabase에서 원하는 데이터를 가져올 수 있는 쿼리 작성

## 추가 정보
추후 추가 예정
