### ISSUE TITLE
Feat. 매거진-토마토 팁 페이지 수정 

### ISSUE THREAD

**Issue by hminah0215** [hminah0215/tomatoes#45]
# Issue 제목

## 설명
- 새로 만들어진 공용 컴포넌트 - 페이지네이션을 사용하여 토마토 팁 페이지 리스트 목록과 곳곳에서 사용되는 지금봐야할 매거진 부분을 수정합니다.
- 공통으로 매거진 페이지에서 사용되는 타입을 별도 정의 합니다 
- 공통으로 매거진 페이지에서 사용되는 데이터 호출 함수를 별도 정의 합니다

## 기대 효과
피그마 파일과 동일한 ui로 구현될것입니다.
pc, 모바일 반응형도 정상적으로 구현될것입니다.

## TODO

- [x] containers>magazine>TomatoTips.tsx 수정 (페이지네이션 컴포넌트 사용)
- [x] containers>magazine>CurrentHighlights.tsx 수정 (페이지네이션 컴포넌트 사용하고 3개만보이게 처리해야함)
- [x] types 폴더 하위에 tomatoTips.ts 작성 
- [x] lib 하위에 데이터 호출 함수 작성
