### ISSUE TITLE
Feat: 검색 페이지 기능 구현

### ISSUE THREAD

**Issue by kitae0831** [hminah0215/tomatoes#48]
## 설명

검색 기능을 구현하여 공모전, 대외활동, 매거진 컨텐츠를 검색할 수 있도록 합니다.

## 기대 효과

- 유저가 검색을 활용하여 필요로하는 정보를 얻을 수 있음

## TODO

- [ ] 검색 페이지 구현
- [ ] 매거진의 경우 html tag를 제거해서 불필요한 정보를 제거하여 정보 제공
- [ ] 추가 데이터를 활용해서 전체 검색이 가능하도록 구현
