### ISSUE TITLE
Feat. 매거진 - 토마토 Pick, 매거진 헤더 

### ISSUE THREAD

**Issue by hminah0215** [hminah0215/tomatoes#51]
## 설명
- 매거진 - 토마토 Pick에 대외활동,공모전 데이터를 불러와 진열합니다. 
- 공통헤더로 작업된 내용을, 매거진에서 정의해서 사용합니다
- 메인레이아웃에 파비콘 이미지(토마토)를 추가합니다.
- 매거진 크롤링 코드를 수정하여 조회수 데이터도 가져옵니다 (검색에서 필요) -> supabase에 조회수 컬럼도 추가해야하고, 타입수정도 해야합니다. 

## 기대 효과
- 반응형을 지원하는 매거진 헤더를 볼 수 있습니다
- 매거진 메인 페이지가 완성됩니다

## TODO

- [x] 매거진 토마토픽 - 공모전,대외활동 데이터 불러와서 그리드 진열 - 페이지네이션
- [x] 메인 레이아웃에 파비콘 이미지 추가 
- [x] 매거진 헤더는 동훈이가 이미 넣어줘서 수정할 필요없음
- [x] 크롤링 코드 수정, json파일 업로드 route 수정, 테이블 컬럼에 맞게 타입 수정
