### ISSUE TITLE
Feat: 대외활동&공모전 페이지 데이터 적용 및 필터 기능 구현

### ISSUE THREAD

**Issue by starcradle101** [hminah0215/tomatoes#53]
## 설명
본 이슈에서는 대외활동&공모전 페이지의 필터 기능과 데이터 페칭 기능을 구현합니다.
기존의 공모전 및 대외활동 페이지의 레이아웃을 개선하고, 추가적으로 상세 페이지에 대한 레이아웃도 구현할 예정입니다.

## 기대 효과
- 이제 반응형을 지원하는 공모전 및 대외활동 페이지를 확인할 수 있습니다
- 공모전 및 대외활동에서 실제 데이터를 불러와 확인할 수 있습니다.

## TODO
- [ ] 공모전 및 대외활동 페이지 레이아웃 개선
- [ ] 공모전 및 대외활동 데이터 페칭 함수 구현
- [ ] 해당 페이지에서 사용하는 컴포넌트 공용화

## 추가 정보
- 레이아웃 개선이 완료되는대로 실제 데이터를 불러와 테스트해볼 예정입니다.
