### ISSUE TITLE
design: 메인 슬라이더/공모전/대외활동 컴포넌트 api 연결

### ISSUE THREAD

**Issue by StopSoo** [hminah0215/tomatoes#55]
## 설명

홈 화면 남은 컴포넌트들 api 연결 및 css 수정 작업 진행.

## TODO

- [x] 메인 슬라이더 api 연결
- [x] 공모전 슬라이더 api 연결 및 css 수정
- [x] 대외활동 슬라이더 api 연결 및 css 수정
- [ ] 매거진 컴포넌트 조정
