### ISSUE TITLE
design: 홈 화면 레이아웃 / 매거진 페이지 css / ‘검색어 없음’ 페이지 쿼리 수정 

### ISSUE THREAD

**Issue by StopSoo** [hminah0215/tomatoes#59]
## TODO

- [X] 매거진/공모전 페이지와 홈 화면의 레이아웃을 일치시킴. ➡️ 마진
- [x] 홈 화면 카테고리 라벨링 css 수정 ⚠️
- [x] 매거진 페이지의 css를 수정.
- [x] '검색어 없음' 페이지 쿼리 수정.
