### ISSUE TITLE
refactor: 발표 전 최종 리팩토링

### ISSUE THREAD

**Issue by StopSoo** [hminah0215/tomatoes#65]
## TODO

- [x] 각 컴포넌트에 상세 페이지 연결.
- [x] 다양한 화면에서의 css 적용 / 반응형 체크.
- [x] css 안 맞는 부분 점검 및 수정.
