### ISSUE TITLE
refactor: 매거진 css 점검, 깃헙액션 설정, 검색창 반응형

### ISSUE THREAD

**Issue by hminah0215** [hminah0215/tomatoes#67]
## 설명

- 매거진 페이지의 다양한 화면에서 보고 수정해야할 부분들을 수정합니다
- 헤더에 있는 검색창을 반응형으로 구현합니다.
- 기존에 작성된 파이썬 크롤링 코드를 깃헙액션으로 자동화하여 2일에 한번씩 업데이트 되도록 설정합니다 

## 기대 효과
- 매거진 페이지의 css 개선
- 검색창을 반응형으로 구현하여 모바일에서는 작은상태로 있다가 검색창을 클릭하면 사용자가 검색어를 입력하기 쉽도록 확장되어야 합니다.  
- 데이터 크롤링 자동화 

## TODO

- [x] 깃헙 액션 자동화를 위한 워크플로우 설정 및 route파일 코드 수정 **(수정했는데 배포가 되어야해서,,, main까지 배포 되어야 실행될거같아유... vercel이 main브랜치만 배포해가지구)** 
- [x] 검색창 반응형 구현 작업
- [x] 크게크게 매거진 페이지 둘러보면서 큰부분만 수정하기,,,, (디테일한 css정리는 발표일 이후에...)
