### ISSUE TITLE
Refactor: 발표 전 리팩토링

### ISSUE THREAD

**Issue by starcradle101** [hminah0215/tomatoes#68]
## 설명
본 이슈에서는 발표 전 @starcradle101 가 맡은 부분에 대한 리팩토링을 진행합니다.

## TODO
- [x] Header CSS 수정
- [x] 게시글 상세페이지 CSS 수정
- [x] 불필요한 console.log 및 주석 삭제 (또는 JSDoc으로 전환)
