### ISSUE TITLE
design: Home / Magazine 리팩토링

### ISSUE THREAD

**Issue by StopSoo** [hminah0215/tomatoes#76]
## TODO

- [x] 메인 슬라이더/모바일 슬라이더 css 작업
    - [x] PC/MO - 제목 배치
    - [x] PC - 포스터와 인포 섹션 배치 수정 및 반응형 적용
    - [x] MO - 버튼 크기 반응형 적용
    - [x] MO - 버튼 누르면 해당 공고 링크로 넘어가게 적용 
    - [x] MO - 포스터를 눌러도 버튼이랑 같은 링크로 넘어가게 적용 
- [x] 홈 화면
    - [x] BEST PICK / 토마토들 추천활동 css 수정
    - [x] 공모전/대외활동 가로 슬라이더
        - [x] 디데이&기간 섹션 고정 배치
        - [x] 공모전 가로 슬라이더 css 수정
        - [x] 제목 두 줄까지만 나오게 하기
        - [x] DB 수정에 따른 fetch 함수 수정하기
- [x] 매거진 CurrentHighlights
    - [x] 작성자 글자 잘리는 문제 해결
- [x] 라벨링 위치 고정 여부 - 화면 크기 별로 체크하기
- [x] 검색 결과 없음 페이지
    - [x] 이미지를 글자로 변경
    - [x] X 버튼 - 홈이 아니라 뒤로 가도록 기능 변경
- [x] 디데이 컴포넌트 
    - [x] 기준 적용
    - [x] 날짜 형식 변경에 따른 css 수정
- [x] 날짜 형식 변경
- [x] 매거진 페이지
    - [x] 더보기 버튼 추가
    - [x] 토마토 Pick css 수정
- [X] 공모전/대외활동 상세 페이지 
    - [x] 탭 및 내용 부분 css 수정 -> 특히 내용 부분이 읽기 힘듬.
