### ISSUE TITLE
Refactor: 페이지네이션 관련 리팩토링

### ISSUE THREAD

**Issue by starcradle101** [hminah0215/tomatoes#77]
## 설명
본 이슈에서는 Supabase 테이블 및 쿼리에 대한 리팩토링과 이를 기반으로 하는 테스트를 진행합니다.

## 기대 효과
- 공모전/대외활동의 테이블을 분리해 더 빠른 쿼리 응답 속도를 가져옵니다.
- 기타 Supabase에서 데이터 페칭 시 개선 가능한 쿼리를 구현합니다.

## TODO
- [ ] 공모전/대외활동 테이블 분리
- [ ] 분리된 테이블 기반 데이터 페칭 테스트
- [ ] Supabase 쿼리 수정 및 불필요한 쿼리 기반 페칭 함수 삭제
