### ISSUE TITLE
Refactor: 검색창 관련 리팩토링

### ISSUE THREAD

**Issue by kitae0831** [hminah0215/tomatoes#78]
## 설명

검색창 일부 조건부로 변환해야하는 부분 변경 및 반응형 작업 진행

## 기대 효과

검색 페이지 내 반응형 구현이 되어 웹 및 특정 크기에서도 원활히 구현
대분류 및 매거진 뱃지 조건부로 변경되어 구분하기 수월해 집니다!
공고문의/등록 내 반응형 구현

## TODO

- [ ] 검색 페이지 반응형 작업
- [ ] 매거진 뱃지 조건부로 변경
- [ ] 대분류[매거진/공모전/대외활동] 조건별 표시
- [ ] 공고문의/등록 화면크기에 따라 이미지 크기 적용하기

**Comment by kitae0831** [comment]
검색창에서 매거진의 Tag를 작성하는데 있어서 컴포넌트를 재사용하고 싶은 목적으로
유틸 함수 getTagLabel.ts를 작성해서 TomatoTipItem의 Hot, New, Best 조건을 뽑아 생성했습니다.
