### ISSUE TITLE
Refactor: 공모전 및 대외활동 페이지

### ISSUE THREAD

**Issue by starcradle101** [hminah0215/tomatoes#84]
## 설명
본 이슈에서는 @starcradle101의 역할 분담으로 진행된 작업에 대한 2차 리팩토링을 진행합니다.
주로 UI 및 레이아웃 위주이며, 오픈그래프 이미지 또는 메타데이터에 대한 수정도 포함합니다.

## 기대 효과
- 이제 대외활동/공모전 아이템의 제목 line-clamp가 정상적으로 작동합니다.
- 대외활동/공모전 아이템의 D-day가 올바르게 표시됩니다.
- 대외활동/공모전 페이지에서 필터를 숨길 수 있습니다.
- 각 페이지별 메타데이터를 확인할 수 있습니다.
- `useScroll` 훅이 더 이상 height에 의존하지 않습니다.
- 일부 컴포넌트에 대한 가독성이 향상됩니다.

## TODO
- [x] 공모전/대외활동 아이템에서 제목 line-clamp 처리 수정
- [x] 공모전/대외활동 아이템에서 Dday 컴포넌트의 올바른 적용
- [ ] 공모전/대외활동 페이지에서 카테고리 필터 숨길 수 있는 기능 구현
- [ ] 이미지 최적화
- [x] 내비게이션 바 숨김 훅인 `useScroll`의 기준을 보다 명확하게 지정할 것
- [x] 스켈레톤 적용
- [x] 컴포넌트 리팩토링
