### ISSUE TITLE
Design: Home/Magazine Refactoring ver.2

### ISSUE THREAD

**Issue by StopSoo** [hminah0215/tomatoes#85]
## 설명

지난 1차 리팩토링 때 완료되지 못 한 부분들과 회의를 통해 추가된 개선점들에 대한 구현을 진행.

## 기대 효과

- DB 수정에 따른 알맞은 데이터 페칭.
- 스켈레톤 적용을 통한 UX 향상.
- 태그 기준 수정을 통한 적절한 데이터 전달 등.

## TODO

- [x] 디데이 컴포넌트 기준 수정
    - [x] 마감
    - [x] 예정은 가능하면 해보기
    - [x] 변경 후 매거진 페이지 / 공모전, 대외활동 상세 페이지에 적용
- [x] 매거진 페이지: 토마토 PICK의 fetch 함수 수정
- [x] 홈 화면의 모든 컴포넌트들 - 공고 id 매칭 수정
- [ ] 스켈레톤 적용 확인해보기
- [x] 모바일 슬라이더 제목 너비 수정하기
- [x] ✳️ 리드미 작성하기 ✳️
