### ISSUE TITLE
Refactor: 매거진 리팩토링 

### ISSUE THREAD

**Issue by hminah0215** [hminah0215/tomatoes#86]
## 설명
1차 리팩토링 후 회의에서 나온 개선점을 토대로 2차 리팩토링 작업

## 기대 효과
- old 페이지네이션에서 개선된 페이지네이션으로 변경 적용
- 스켈레톤 적용으로 ux 개선 
- 크롤링 관련 자동화 작업 개선 

## TODO
- [x] 매거진 토마토TIP, 토마토PICK 페이지네이션 변경 적용하기 
- [x] 스켈레톤 적용
- [x] 매거진 데이터 크롤링 자동화가 잘 적용되어 4일에 한번 데이터를 다시 크롤링하고 supabase 테이블에 있는 데이터를 다 지운 후 다시 insert하게 되어있는데, 그 부분을 좀 더 좋은 방법(?)으로 개선
- [x] 리드미 작성 ( #75 브랜치에서)
