### ISSUE TITLE
Feat: '검색 결과 없음' 페이지 구현 작업

### ISSUE THREAD

**Issue by StopSoo** [hminah0215/tomatoes#9]
## 설명
'검색 결과 없음' 페이지 구현 작업

## 기대 효과
사용자가 입력한 검색어에 대한 결과가 없을 경우, 이미지를 통해 확실하게 전달 가능.

## TODO
- [x] 페이지에 필요한 asset 정리 
- [x] 페이지 디자인 수정 
- [ ] ‘검색 결과 없음’ 페이지 구성

## 추가 정보
<img width="595" alt="Screenshot 2024-10-16 at 14 37 05" src="https://github.com/user-attachments/assets/64b92d5b-919f-4043-9966-d3937df1ef71">
